apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app
  labels:
    app: dep-app
spec:
  replicas: 2
  template:
    metadata:
      name: dep-app
      labels:
        app: dep-app
    spec:
      containers:
        - name: dep-app
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: dep-app

---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
spec:
  selector:
    app: dep-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
